scriptify the git clone sample

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -35,16 +35,24 @@ workflows:
     after_run:
     - _common_test
     steps:
-    - git-clone:
-        run_if: true
+    - script:
         inputs:
-        - repository_url: $SAMPLE_APP_URL
-        - clone_into_dir: "$ORIG_BITRISE_SOURCE_DIR/_tmp"
-        - commit: ""
-        - tag: ""
-        - branch: $BRANCH
-        - pull_request_id: ""
-        - clone_depth: ""
+        - content: |-
+            #!/usr/bin/env bash
+
+            if [[ -z "${SAMPLE_APP_URL}" ]]; then
+            echo "error: there is no SAMPLE_APP_URL env var specified"
+            exit 1
+            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
+            echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
+            exit 1
+            fi
+
+            git init
+            git remote add origin "${SAMPLE_APP_URL}" 
+            git fetch || exit 1
+
+            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
     - nuget-restore:
         inputs:
         - nuget_version: ""
@@ -94,16 +102,24 @@ workflows:
     after_run:
     - _common_test
     steps:
-    - git-clone:
-        run_if: true
+    - script:
         inputs:
-        - repository_url: $SAMPLE_APP_URL
-        - clone_into_dir: "$ORIG_BITRISE_SOURCE_DIR/_tmp"
-        - commit: $COMMIT
-        - tag: ""
-        - branch: $BRANCH
-        - pull_request_id: ""
-        - clone_depth: ""
+        - content: |-
+            #!/usr/bin/env bash
+
+            if [[ -z "${SAMPLE_APP_URL}" ]]; then
+            echo "error: there is no SAMPLE_APP_URL env var specified"
+            exit 1
+            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
+            echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
+            exit 1
+            fi
+
+            git init
+            git remote add origin "${SAMPLE_APP_URL}" 
+            git fetch || exit 1
+
+            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
     - xcode-archive:
         inputs:
         - force_team_id: $FORCE_TEAM_ID
@@ -128,16 +144,24 @@ workflows:
     after_run:
     - _common_test
     steps:
-    - git-clone:
-        run_if: true
+    - script:
         inputs:
-        - repository_url: $SAMPLE_APP_URL
-        - clone_into_dir: "$ORIG_BITRISE_SOURCE_DIR/_tmp"
-        - commit: $COMMIT
-        - tag: ""
-        - branch: $BRANCH
-        - pull_request_id: ""
-        - clone_depth: ""
+        - content: |-
+            #!/usr/bin/env bash
+
+            if [[ -z "${SAMPLE_APP_URL}" ]]; then
+            echo "error: there is no SAMPLE_APP_URL env var specified"
+            exit 1
+            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
+            echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
+            exit 1
+            fi
+
+            git init
+            git remote add origin "${SAMPLE_APP_URL}" 
+            git fetch || exit 1
+
+            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
     - xcode-archive:
         inputs:
         - force_team_id: $FORCE_TEAM_ID
