[STEP-2081] Fallback profiles (#66)
* Added Fallback provisining profiles (fallback_provisioning_profile_url_list) input.
If set, provided provisioning profiles will be used on Automatic code signing error.

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -111,6 +111,8 @@ workflows:
   test_auto_codesign_with_manual_assets:
     before_run:
     - _setup
+    - _backup_api_envs
+    - _invalid_login
     steps:
     - certificate-and-profile-installer:
         inputs:
@@ -129,28 +131,18 @@ workflows:
         - min_profile_validity: 30
         - certificate_url_list: $BITFALL_APPLE_APPLE_CERTIFICATE_URL_LIST
         - passphrase_list: $BITFALL_APPLE_APPLE_CERTIFICATE_PASSPHRASE_LIST
+        - fallback_provisioning_profile_url_list: $BITFALL_APPLE_PROVISIONING_PROFILE_URL_LIST
         - keychain_path: $BITRISE_KEYCHAIN_PATH
         - keychain_password: $BITRISE_KEYCHAIN_PASSWORD
+    after_run:
+    - _restore_api_envs
 
   test_auto_codesign:
     before_run:
     - _setup
-    - _expose_xcode_version
     steps:
-    - script:
-        inputs:
-        - content: |-
-            #!/bin/env bash
-            set -e
-            if [[ ${XCODE_MAJOR_VERSION} -lt 13 ]]; then
-              echo "This test case requires Xcode >= 13, skipping..."
-              exit 0
-            fi
-            envman add --key XCODE_MAJOR_VERSION_AT_LEAST_13 --value "true"
     - path::./:
-        title: Step Test - Multi Target xcodebuild auto signing
-        run_if: |-
-          {{ enveq "XCODE_MAJOR_VERSION_AT_LEAST_13" "true" }}
+        title: Step Test - Multi Target xcodebuild auto signing (XCode 13+)
         inputs:
         - distribution_method: development
         - archive_path: ./archives/Fruta-managed.xcarchive
@@ -254,24 +246,41 @@ workflows:
         - clone_into_dir: .
         - branch: $SAMPLE_ARTIFACTS_BRANCH
 
-  _expose_xcode_version:
+  _invalid_login:
     steps:
     - script:
-        title: Expose Xcode major version
+        title: Set invalid login
         inputs:
         - content: |-
             #!/bin/env bash
-            set -e
-            if [[ ! -z "$XCODE_MAJOR_VERSION" ]]; then
-              echo "Xcode major version already exposed: $XCODE_MAJOR_VERSION"
-              exit 0
-            fi
-            version=`xcodebuild -version`
-            regex="Xcode ([0-9]*)."
-            if [[ ! $version =~ $regex ]]; then
-              echo "Failed to determine Xcode major version"
-              exit 1
-            fi
-            xcode_major_version=${BASH_REMATCH[1]}
-            echo "Xcode major version: $xcode_major_version"
-            envman add --key XCODE_MAJOR_VERSION --value $xcode_major_version
+            set -ex
+            INVALID_BUILD_URL=./_invalid_authinfo
+            echo '{"key_id": "x", "issuer_id": "x", "private_key": "x"}' > $INVALID_BUILD_URL
+
+            BITRISE_BUILD_URL="file://$INVALID_BUILD_URL"
+            BITRISE_BUILD_API_TOKEN="x"
+
+            envman add --key BITRISE_BUILD_URL --value $BITRISE_BUILD_URL
+            envman add --key BITRISE_BUILD_API_TOKEN --value $BITRISE_BUILD_API_TOKEN
+
+  _backup_api_envs:
+    steps:
+    - script:
+        title: Backup Bitrise API connection env vars
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -ex
+            envman add --key BITRISE_BUILD_URL_BACKUP --value $BITRISE_BUILD_URL
+            envman add --key BITRISE_BUILD_API_TOKEN_BACKUP --value $BITRISE_BUILD_API_TOKEN
+
+  _restore_api_envs:
+    steps:
+    - script:
+        title: Restore Bitrise API connection env vars
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -ex
+            envman add --key BITRISE_BUILD_URL --value $BITRISE_BUILD_URL_BACKUP
+            envman add --key BITRISE_BUILD_API_TOKEN --value $BITRISE_BUILD_API_TOKEN_BACKUP
